### ISSUE TITLE
Latest version gives run time error

### ISSUE THREAD

**Issue by avi312singh** [dsyomichev/source-server-query#11] opened 2022-04-24 18:10 UTC
Hi i have upgraded from 1.0.1 to 2.1.4 but seem to be getting an error at run time

Was there any breaking changes from v1 to v2 or migration guides - i cant seem to find any?

So here is the error i am getting with the exact same code that is working in 1.0.1: 

`                    await query
                        .players(serverIp, 7778, 800)
                        .then(query.close)
                        .catch(console.error);`

`Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at new NodeError (node:internal/errors:371:5)
    at healthCheck (node:dgram:900:11)
    at Socket.send (node:dgram:634:3)
    at /Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/index.js:21:12
    at new Promise (<anonymous>)
    at send (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/index.js:5:10)
    at challenge (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/index.js:43:26)
    at Object.module.exports.players (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/index.js:156:23)
    at module.exports (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routesUtils/serverStatsUtils/serverStats.js:25:26)
    at async /Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routes/serverstats.js:49:5 {
  code: 'ERR_SOCKET_DGRAM_NOT_RUNNING'
}
`

This is what i am catching: 
`Sending default response as error has occurred whilst fetching a set of new players with error: TypeError: Cannot read properties of undefined (reading 'length')`

I have tried 2.14 and 2.1.3 and they both seem to be giving me the same error so i will stay at 1.0.1 for now 😢 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5769090/164990396-f307addc-af0f-4b2f-a3bd-e0a148440d7a.png">

**Comment by dsyomichev** [comment] 2022-04-25 18:04
I don't believe the API changed. Everything looks alright, but I don't believe you need the await with a then/catch. It could be something about the state of the response. Are there non standard characters in the player names or maybe no players on the server? I will do some more digging.

**Comment by avi312singh** [comment] 2022-04-25 21:33
I've been doing some debugging... 
Try running this snippet of code twice in a row:
`        const directQueryInfo =
            query
                .info('79.98.25.135', 7778, 800)
                .then(console.log)
                .then(query.close)
                .catch(console.error);
        return directQueryInfo`

I have got this in an express endpoint and the second time this endpoint is called, i get the same error... i attached a screenshot of the code i am running along with the terminal output on the first and second run through

so it seems after the first run of code in a web server it will fail after that
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5769090/165177997-4ca0a3e8-bb5e-4b5a-8d79-5d28a6574cae.png">

**Comment by avi312singh** [comment] 2022-04-25 21:37
The error being thrown with a proper try catch is:
`Sending default response as error has occurred whilst fetching a set of new players with error: TypeError: Cannot read properties of undefined (reading 'length')`

https://github.com/avi312singh/FTYD-Express-App/blob/main/routesUtils/serverStatsUtils/serverStats.js#L36

**Comment by dsyomichev** [comment] 2022-04-26 11:27
No the second issue isn’t intended, but should be a quick fix. The socket
not running error however I’m not sure at all about. I will look into it
later today.

**Comment by avi312singh** [comment] 2022-04-27 08:57
Sure, it looks similar to this issue - https://github.com/emilianomaccaferri/minecraft-query/issues/4#issuecomment-542774853

**Comment by dsyomichev** [comment] 2022-05-29 22:42
So sorry for the extremely long reply, I've been incredibly busy. I pushed a new update to NPM that addresses the closing behavior of the socket. Hopefully, this should resolve the socket not open error, as well as just make the library easier to use.  The caveat is that because of the delay, I pushed the update without testing it thoroughly so I'm going to keep this issue open until I can confirm that everything is working as expected. 

Also, with the new behavior, the socket will close automatically when there are no requests hanging, and reopen on the next request. This basically means that the .finally(socket.close()) is unnecessary.

**Closed as completed** 2022-06-19 17:59 UTC

**Comment by avi312singh** [comment] 2022-07-11 12:42
hi I want to reopen this, if I upgrade to latest version I get error: TypeError: query.players is not a function

I have had to revert back to 1.0.1 again with no code changes and it works perfectly fine... :(

**Comment by dsyomichev** [comment] 2022-07-11 12:54
It’s a typescript export now. Use:

const query = require(“source-server-query”).default

**Comment by avi312singh** [comment] 2022-07-11 13:27
Ok I should have seen that my bad, now i get this:
`TypeError: Cannot read properties of undefined (reading 'socket')
    at close (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/dist/index.js:69:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routesUtils/serverStatsUtils/serverStats.js:22:25)
    at async /Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routes/serverstats.js:78:3
TypeError: Cannot read properties of undefined (reading 'socket')
    at close (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/node_modules/source-server-query/dist/index.js:69:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routesUtils/serverStatsUtils/serverStats.js:26:26)
    at async /Users/avirajmandair/Downloads/dev/discord-bot-sitepoint/routes/serverstats.js:78:3
Sending default response as error has occurred whilst fetching a set of new players with error: TypeError: Cannot set properties of undefined (setting 'status')`

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5769090/178274997-71bdbb85-73e2-4022-86d8-53c5af3b8ee0.png">

**Comment by dsyomichev** [comment] 2022-07-11 22:08
Can you show where you're using and closing the socket?

Edit: I can only reproduce this when using something like:

```query.players('xxx.xxx.xxx.xxx', 27015, 1000).finally(query.close);``` (`query.close`)

rather than

```query.players('xxx.xxx.xxx.xxx', 27015, 1000)**.finally(() => query.close());``` (`() => query.close();`)
