### ISSUE TITLE
After removing the bufferpack, the "players" function has broken

### ISSUE THREAD

**Issue by Deellay** [dsyomichev/source-server-query#8] opened 2022-03-16 21:50 UTC
After the last update, the withdrawal of players does not work correctly. CS:GO TV outputs 2 times, without a nickname and one of them has a huge false duration

**Comment by dsyomichev** [comment] 2022-03-16 21:55
I need more information than that. Upload the output

**Comment by dsyomichev** [comment] 2022-03-17 00:39
I found the issue in the players function but i'm not sure of the issue you're having with the tv information. The tvname and tvport are working without issues with the servers Im testing.

**Comment by dsyomichev** [comment] 2022-03-20 21:59
Im going to close this.  I don't know what the issue is.

**Closed as completed by dsyomichev** 2022-03-20 21:59 UTC
